import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import LegacyLogic from "@/components/LegacyLogic";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Legacy CSS */}
        <link rel="stylesheet" href="/static/csshet/bootstrap.min.css" />
        <link rel="stylesheet" href="/static/csshet/nice-select.css" />
        <link rel="stylesheet" href="/static/csshet/font-awesome.min.css" />
        <link rel="stylesheet" href="/static/csshet/icofont.css" />
        <link rel="stylesheet" href="/static/csshet/slicknav.min.css" />
        <link rel="stylesheet" href="/static/csshet/owl-carousel.css" />
        <link rel="stylesheet" href="/static/csshet/datepicker.css" />
        <link rel="stylesheet" href="/static/csshet/animate.min.css" />
        <link rel="stylesheet" href="/static/csshet/magnific-popup.css" />
        <link rel="stylesheet" href="/static/csshet/normalize.css" />
        <link rel="stylesheet" href="/static/style.css" />
        <link rel="stylesheet" href="/static/csshet/responsive.css" />

        {/* Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="js" suppressHydrationWarning>
        <Providers>{children}</Providers>

        {/* Legacy Scripts */}
        <Script src="/static/jscript/jquery.min.js" strategy="beforeInteractive" />
        <Script src="/static/jscript/jquery-migrate-3.0.0.js" strategy="afterInteractive" />
        <Script src="/static/jscript/jquery-ui.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/easing.js" strategy="afterInteractive" />
        <Script src="/static/jscript/colors.js" strategy="afterInteractive" />
        <Script src="/static/jscript/popper.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/bootstrap-datepicker.js" strategy="afterInteractive" />
        <Script src="/static/jscript/jquery.nav.js" strategy="afterInteractive" />
        <Script src="/static/jscript/slicknav.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/jquery.scrollUp.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/niceselect.js" strategy="afterInteractive" />
        <Script src="/static/jscript/tilt.jquery.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/owl-carousel.js" strategy="afterInteractive" />
        <Script src="/static/jscript/jquery.counterup.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/steller.js" strategy="afterInteractive" />
        <Script src="/static/jscript/wow.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/jquery.magnific-popup.min.js" strategy="afterInteractive" />
        <Script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js" strategy="afterInteractive" />
        <Script src="/static/jscript/bootstrap.min.js" strategy="afterInteractive" />

        {/* Main JS logic moved to LegacyLogic component */}
        <LegacyLogic />
      </body>
    </html >
  );
}
